source 'git@github.com:CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'UIActionKit_Example' do
  pod 'UIActionKit', :path => '../'

  target 'UIActionKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
